### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by michaelhwhitten** [ojousima/node-red#1]
Hi Otso,

No doubt I'm doing something wrong but am having a little trouble with the installation. I've followed the directions a couple times but the Ruuvi node won't show up in the graphical palette manager. 

When using the hamburger menu and going to "Manage palette" I do see:
node-red-contrib-ruuvitag
0.0.2
 1 node
    lowercase

The node seems to be getting lost; there's no icon and the name is "lowercase."

When I stop node-red by hand and restart it I do get:
19 May 10:59:47 - [warn] ------------------------------------------------------
19 May 10:59:47 - [warn] [ruuvitag] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
19 May 10:59:47 - [warn] ------------------------------------------------------

I'm not sure if that matters or not. Thanks in advance for any help and definitely for writing this node so quickly!
Mike

**Comment by michaelhwhitten** [comment]
Hey Otso -

I've been looking at this. Re the "lowercase" I think that's a leftover in the html file from the node-red example. I changed it to ruuvitag locally and that went away.

Re the syntax warnings - it may well be that my node.js and node-red are far enough behind to cause that. I'm working on upgrading them now.

Mike

**Comment by michaelhwhitten** [comment]
Ah, a thing of beauty. ;) After updating my Pi it's working fine. Thank you!

The only minor thing remaining is the "lowercase" mentioned above; truly trivial. Hope you have/had a great weekend.

Mike

**Comment by ojousima** [comment]
Thank you for the help, The "lowercase" is fixed in  52bd0e2e789e74985fda401bda0ba1bdb8526516. I'll look into dependency management to avoid issues with older versions of NodeJS and Node Red.

Have a nice weekend,
Otso
