### ISSUE TITLE
[Node-RED] Ruuvi Tag via Ruuvi Gateway HTTP

### ISSUE THREAD

**Issue by rudam** [ojousima/node-red#13]
Hi. I made a Node-RED flow to decode the Ruuvi Tag data from the Ruuvi Gateway via HTTP transport.
Regards,
Michal

![image](https://user-images.githubusercontent.com/18708947/132891948-1b816686-e03e-4524-a50b-5a89e9061ab0.png)

`[{"id":"2a0aad5f.9a6202","type":"http in","z":"d6fd07cd.c7de28","name":"","url":"/ruuvi-gw","method":"post","upload":false,"swaggerDoc":"","x":120,"y":580,"wires":[["b80b298d.a36668","4c091efe.c3845","44043b05d6bc76aa"]]},{"id":"ccb90b199b050948","type":"ruuvitag","z":"d6fd07cd.c7de28","name":"","x":900,"y":580,"wires":[["43478f78e25b5d91"]]},{"id":"731f9a22f4b02f24","type":"debug","z":"d6fd07cd.c7de28","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1350,"y":580,"wires":[]},{"id":"44043b05d6bc76aa","type":"change","z":"d6fd07cd.c7de28","name":"Header","rules":[{"t":"set","p":"header.gw_mac","pt":"msg","to":"payload.data.gw_mac","tot":"msg"},{"t":"set","p":"header.timestamp","pt":"msg","to":"$number(payload.data.timestamp)","tot":"jsonata"},{"t":"set","p":"payload","pt":"msg","to":"payload.data.tags","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":580,"wires":[["771b7603268a132e","260274ce1ffc231e"]]},{"id":"771b7603268a132e","type":"split","z":"d6fd07cd.c7de28","name":"","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","x":470,"y":580,"wires":[["0d6ed72cca498162","5f6d101c33cb7f0c"]]},{"id":"be7c53c8574ec4f4","type":"json","z":"d6fd07cd.c7de28","name":"","property":"payload","action":"","pretty":false,"x":750,"y":580,"wires":[["ccb90b199b050948"]]},{"id":"43478f78e25b5d91","type":"json","z":"d6fd07cd.c7de28","name":"","property":"payload","action":"","pretty":false,"x":1050,"y":580,"wires":[["a38a7c26d80cc7a4"]]},{"id":"5f6d101c33cb7f0c","type":"change","z":"d6fd07cd.c7de28","name":"Clean","rules":[{"t":"set","p":"topic","pt":"msg","to":"parts.key","tot":"msg"},{"t":"delete","p":"req","pt":"msg"},{"t":"delete","p":"res","pt":"msg"},{"t":"delete","p":"parts","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":610,"y":580,"wires":[["be7c53c8574ec4f4"]]},{"id":"a38a7c26d80cc7a4","type":"change","z":"d6fd07cd.c7de28","name":"Move","rules":[{"t":"set","p":"payload.gw_mac","pt":"msg","to":"header.gw_mac","tot":"msg"},{"t":"set","p":"payload.timestamp","pt":"msg","to":"header.timestamp","tot":"msg"},{"t":"delete","p":"header","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1190,"y":580,"wires":[["731f9a22f4b02f24"]]},{"id":"b80b298d.a36668","type":"http response","z":"d6fd07cd.c7de28","name":"OK","statusCode":"204","headers":{},"x":310,"y":540,"wires":[]}]`

**Comment by ojousima** [comment]
Is your code available somewhere publicly? I could archive this repository and point users to yours if it is better maintained and contains similar functionality

**Comment by rudam** [comment]
> Is your code available somewhere publicly? I could archive this repository and point users to yours if it is better maintained and contains similar functionality

Hi. What I did, and post here is the Node-RED flow, which uses your ruuvi-node. There is no new code.
