### ISSUE TITLE
Please rename GitHub repo to node-red-contrib-ruuvitag

### ISSUE THREAD

**Issue by jannylund** [ojousima/node-red#3]
Please rename GitHub repo to node-red-contrib-ruuvitag. It's very confusing now when cloning it and it goes into a folder node-red.

**Comment by ojousima** [comment]
This repository was originally meant for quick'n'dirty prrof-of-concepting only, hence the name. I do agree that the name is confusing, though. We'll move the repository under Ruuvi's account, update the links in tutorials and rename the repo. This will take a short while.
