### ISSUE TITLE
MAC Address missing

### ISSUE THREAD

**Issue by Sotaur** [ojousima/node-red#4]
It would be helpful to also output the device so you can identify which device the data came from. I've got code that'll take the msg object and add the MAC address to the returned data.

**Comment by ojousima** [comment]
Can you open a pull request? 
I'm pretty swamped right now so I cannot probably work on this for a while

**Comment by Sotaur** [comment]
Yeah, I can do that.

**Comment by ojousima** [comment]
Solved in #5, thanks.
